version: 2

jobs:
  build:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            make clean
            make deps
      - run:
          name: Run Tests
          command: |
            make coverage
